# 需要注意的是，所有的修改，都填在引号里面
application:
  name: ''
  qmsgd:
    qmsg: 'xxxxxx' #也可以改成其他的，比如163邮箱
  weather:
    appid: '849xx' #在www.tianqiapi.com申请的appid
    appsecret: 'n6exxx' #在www.tianqiapi.com申请的appsecret
girlfriend:

  city: 'xxx' #你女票所在的城市
  start_love_date: "xxxx" #开始在一起的日期，格式"2020-05-15"，请保持一致
  date_msg: '我们俩在一起的第%d天' #要不要改，你们看着办，但必须要有%d，可以参考index.py中获取模板消息的函数
  nickname: 'xxx' #对你的女票的爱称
  sweet_nickname: 'xxx' #你在你女票那里的称呼

